version: '3.8'

services:
  bot:
    build: .
    container_name: flowerbot
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./levels.db:/app/levels.db
      - ./config.json:/app/config.json
      - ./discord.log:/app/discord.log
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"
